/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using KochWermann.SKS.Package.Services.Attributes;
using Microsoft.Extensions.Logging;
using AutoMapper;
using KochWermann.SKS.Package.BusinessLogic.Interfaces;
using System;

namespace KochWermann.SKS.Package.Services.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class LogisticsPartnerApiController : ControllerBase
    { 
        private readonly IMapper _mapper;
        private readonly ITrackingLogic _trackingLogic;
        private readonly ILogger<LogisticsPartnerApiController> _logger;

        
        /// <summary>
        /// 
        /// </summary>
        public LogisticsPartnerApiController(IMapper mapper, ITrackingLogic trackingLogic, ILogger<LogisticsPartnerApiController> logger)
        {
            _mapper = mapper;
            _trackingLogic = trackingLogic;
            _logger = logger;
            _logger.LogTrace("LogisticsPartnerApiController created");
        }

        /// <summary>
        /// Transfer an existing parcel into the system from the service of a logistics partner. 
        /// </summary>
        /// <param name="body"></param>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <response code="200">Successfully transitioned the parcel</response>
        /// <response code="400">The operation failed due to an error.</response>
        [HttpPost]
        [Route("/parcel/{trackingId}")]
        [ValidateModelState]
        [SwaggerOperation("TransitionParcel")]
        [SwaggerResponse(statusCode: 200, type: typeof(DTOs.NewParcelInfo), description: "Successfully transitioned the parcel")]
        [SwaggerResponse(statusCode: 400, type: typeof(DTOs.Error), description: "The operation failed due to an error.")]
        public virtual IActionResult TransitionParcel([FromBody]DTOs.Parcel body, [FromRoute][Required][RegularExpression("^[A-Z0-9]{9}$")]string trackingId)
        {            
            try
            {
                _logger.LogTrace($"TransitionParcel: trackingId: {trackingId}");

                if (body == null)
                {
                    _logger.LogError("Parcel is null");
                    return BadRequest(new DTOs.Error{ErrorMessage = "Parcel is null"});
                }

                if (string.IsNullOrWhiteSpace(trackingId))
                {
                    _logger.LogError("TrackingId is null or white space");
                    return BadRequest(new DTOs.Error{ErrorMessage = "TrackingId is null or white space"});
                }

                var blParcel = _mapper.Map<BusinessLogic.Entities.Parcel>(body);
                var blTransitionedParcel = _trackingLogic.TransitionParcel(blParcel, trackingId);
                var serviceNewParcelInfo = _mapper.Map<DTOs.NewParcelInfo>(blTransitionedParcel);

                return Ok(serviceNewParcelInfo);
            }
            catch (Exception ex)
            {
                _logger.LogError($"The operation failed due to an error {ex}");
                return BadRequest(new DTOs.Error{ErrorMessage = "The operation failed due to an error"});
            }
        }

    }
}

