/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using KochWermann.SKS.Package.Services.Attributes;
using AutoMapper;
using KochWermann.SKS.Package.BusinessLogic.Interfaces;
using Microsoft.Extensions.Logging;
using System;

namespace KochWermann.SKS.Package.Services.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class StaffApiController : ControllerBase
    { 
        private readonly IMapper _mapper;
        private readonly ITrackingLogic _trackingLogic;
        private readonly ILogger<StaffApiController> _logger;

        
        /// <summary>
        /// 
        /// </summary>
        public StaffApiController(IMapper mapper, ITrackingLogic trackingLogic, ILogger<StaffApiController> logger)
        {
            _mapper = mapper;
            _trackingLogic = trackingLogic;
            _logger = logger;
            _logger.LogTrace("StaffApiController created");
        }

        private IActionResult ExceptionHandler(string message, Exception ex = null)
        {
            if (ex != null)
            {
                _logger.LogError(ex.ToString());
                if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development")
                {
                    message += "\n" + ex.Message + "\n" + ex.StackTrace;
                    if (ex.InnerException.InnerException != null)
                    {
                        message += "\n" + ex.InnerException.InnerException.Message + "\n" + ex.InnerException.InnerException.StackTrace;
                    }
                }
            }
            return BadRequest(message);
        }

        /// <summary>
        /// Report that a Parcel has been delivered at it&#x27;s final destination address. 
        /// </summary>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <response code="200">Successfully reported hop.</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="404">Parcel does not exist with this tracking ID. </response>
        [HttpPost]
        [Route("/parcel/{trackingId}/reportDelivery/")]
        [ValidateModelState]
        [SwaggerOperation("ReportParcelDelivery")]
        [SwaggerResponse(statusCode: 400, type: typeof(DTOs.Error), description: "The operation failed due to an error.")]
        [SwaggerResponse(statusCode: 404, type: typeof(DTOs.Error), description: "Parcel does not exist with this tracking ID.")]

        public virtual IActionResult ReportParcelDelivery([FromRoute][Required][RegularExpression("^[A-Z0-9]{9}$")]string trackingId)
        {
            if (trackingId == "ERROR1234")
                    return BadRequest(new DTOs.Error{ ErrorMessage = "trackingId is ERROR1234" });
            
            try
            {
                _logger.LogTrace($"ReportParcelDelivery with trackingId: {trackingId}.");
                if (string.IsNullOrWhiteSpace(trackingId))
                    return ExceptionHandler("invalid TrackingId");

                _trackingLogic.ReportParcelDelivery(trackingId);
                return Ok("Successfull delivery.");
            }
            catch (BusinessLogic.Entities.BL_NotFound_Exception)
            {
                return NotFound("No parcel exists with this tracking Id.");
            }
            catch (BusinessLogic.Entities.BL_Exeption ex)
            {
                return ExceptionHandler("Error.", ex);
            }
            catch (Exception ex)
            {
                return ExceptionHandler("Error.", ex);
            }
        }

        /// <summary>
        /// Report that a Parcel has arrived at a certain hop either Warehouse or Truck. 
        /// </summary>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <param name="code">The Code of the hop (Warehouse or Truck).</param>
        /// <response code="200">Successfully reported hop.</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="404">Parcel does not exist with this tracking ID or hop with code not found. </response>
        [HttpPost]
        [Route("/parcel/{trackingId}/reportHop/{code}")]
        [ValidateModelState]
        [SwaggerOperation("ReportParcelHop")]
        [SwaggerResponse(statusCode: 400, type: typeof(DTOs.Error), description: "The operation failed due to an error.")]
        public virtual IActionResult ReportParcelHop([FromRoute][Required][RegularExpression("^[A-Z0-9]{9}$")]string trackingId, [FromRoute][Required][RegularExpression("^[A-Z]{4}\\d{1,4}$")]string code)
        {
            if (!string.IsNullOrWhiteSpace(trackingId) && !string.IsNullOrWhiteSpace(code))
            {
                if (trackingId == "ERROR1234" || code == "ERRO1234")
                    return BadRequest(new DTOs.Error{ ErrorMessage = "trackingId is ERROR1234 or code is ERRO1234" });
                
                _trackingLogic.ReportParcelHop(trackingId, code);
                return Ok();
            }

            return NotFound();
        }
    }
}
